version: '3.3'
networks:
  backend:
    driver: bridge
volumes:
  postgres_data:
    driver: local
services:
  app:
    build: .
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/test_db
      spring.datasource.username: postgres
      spring.datasource.password: password
      spring.jpa.hibernate.ddl-auto: create
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata